name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping -h 127.0.0.1 -P 3306 --silent; do
          sleep 1
        done
    
    - name: Set up test database
      env:
        RLWY_HOST: 127.0.0.1
        RLWY_USER: root
        RLWY_PASS: root
        RLWY_DB: test_db
        RLWY_PORT: 3306
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -proot test_db < server/sql/table_setup.sql
    
    - name: Run tests
      env:
        RLWY_HOST: 127.0.0.1
        RLWY_USER: root
        RLWY_PASS: root
        RLWY_DB: test_db
        RLWY_PORT: 3306
      run: |
        pytest --cov=./ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3